[workspace]
allow_dirty = false
changelog_update = true
git_release_enable = true
git_tag_enable = true
publish = true
publish_allow_dirty = false
git_release_type = "auto"
semver_check = true

[changelog]
header = """# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""
body = """
## [{{ version }}]\
{%- if previous %} - {{ now() | date(format="%Y-%m-%d") }}{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {%- if commit.scope %} **({{ commit.scope }})**{% endif %} {{ commit.message | upper_first }}
{%- endfor %}
{% endfor %}
"""
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^test", group = "Tests" },
    { message = "^chore", skip = true },
    { message = "^ci", skip = true },
    { message = "^style", skip = true },
]
